# Replace the text below to customize your site
site_name: Niyomugenga-URACEIoT/
site_description: Niyomugenga Grace - Modeling & Fabrication Documentation
site_author: Niyomugenga Grace
copyright: Copyright 2026 Niyomugenga Grace - Creative Commons Attribution Non-commercial

site_url: https://niyomugenga92.github.io/Niyomugenga-URACEIoT/
repo_url: https://github.com/niyomugenga92/Niyomugenga-URACEIoT
repo_name: niyomugenga92/Niyomugenga-URACEIoT

extra:
  social:
    # Change to your own social media or remove line to hide. 
    # For more social icons ideas at https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fablab_rwanda
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/KigaliFabLab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fablabrw

theme:
  # The name of the theme, needs to match your requirements.txt file
  name: material
  # Material theme options:
  palette:
    # try other colors from https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    primary: teal
    accent: deep purple
  font:
    # See available fonts from https://fonts.google.com/
    text: Montserrat
    code: Roboto Mono
  icon:
    # Read about icons at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
    logo: material/library
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.footer

# Read more here https://squidfunk.github.io/mkdocs-material/customization/#additional-css 
extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - 'javascript/extra.js'

plugins:
  - search
  - glightbox:
  - git-revision-date:
      enabled_if_env: CI

# See more extensions at https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - meta

# Navigation structure
nav:
  - Home: index.md
  - Daily Activities:
    - Overview: Daily-Activity/index.md
    - Day 1 - Foundations of Modeling & Fabrication: Daily-Activity/day_1.md
    - Day 2 - Digital Modeling for Fabrication: Daily-Activity/day_2.md
    - Day 3 - Technical Documentation & Quality Control: Daily-Activity/day_3.md
    - Day 4 - Materials & Fabrication Methods: Daily-Activity/day_4.md
    - Day 5 - Digital Fabrication I - CNC & Laser Cutting: Daily-Activity/day_5.md
    - Day 6 - Digital Fabrication II - Additive Manufacturing: Daily-Activity/day_6.md
    - Day 7 - Digital Fabrication III - CNC Router Milling: Daily-Activity/day_7.md
    - Day 8 - Finishing & Surface Enhancement: Daily-Activity/day_8.md
    - Day 9 - Final Presentation & Documentation: Daily-Activity/day_9.md
